[package]
name = "exercises_for_programmer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
once_cell = "1.21.3"
regex = "1"
rand = "0.8"